# Generated by Django 3.0 on 2022-05-17 10:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringColleges4May',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('field_1', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=254, null=True)),
                ('postaladdr', models.CharField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('management', models.CharField(blank=True, max_length=254, null=True)),
                ('yesno1', models.CharField(blank=True, max_length=254, null=True)),
                ('yesno2', models.CharField(blank=True, max_length=254, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'engineering_colleges_4may',
                'managed': False,
            },
        ),
    ]
